/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/sky': RouteRecordInfo<'/albums/sky', '/albums/sky', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/fan/': RouteRecordInfo<'/fan/', '/fan', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/迭代-递归-分治': RouteRecordInfo<'/posts/迭代-递归-分治', '/posts/迭代-递归-分治', Record<never, never>, Record<never, never>>,
    '/posts/对链表插入排序': RouteRecordInfo<'/posts/对链表插入排序', '/posts/对链表插入排序', Record<never, never>, Record<never, never>>,
    '/posts/反转部分链表': RouteRecordInfo<'/posts/反转部分链表', '/posts/反转部分链表', Record<never, never>, Record<never, never>>,
    '/posts/反转链表': RouteRecordInfo<'/posts/反转链表', '/posts/反转链表', Record<never, never>, Record<never, never>>,
    '/posts/合并有序链表': RouteRecordInfo<'/posts/合并有序链表', '/posts/合并有序链表', Record<never, never>, Record<never, never>>,
    '/posts/回文数': RouteRecordInfo<'/posts/回文数', '/posts/回文数', Record<never, never>, Record<never, never>>,
    '/posts/机器学习': RouteRecordInfo<'/posts/机器学习', '/posts/机器学习', Record<never, never>, Record<never, never>>,
    '/posts/决策树': RouteRecordInfo<'/posts/决策树', '/posts/决策树', Record<never, never>, Record<never, never>>,
    '/posts/链表': RouteRecordInfo<'/posts/链表', '/posts/链表', Record<never, never>, Record<never, never>>,
    '/posts/链表排序': RouteRecordInfo<'/posts/链表排序', '/posts/链表排序', Record<never, never>, Record<never, never>>,
    '/posts/排序': RouteRecordInfo<'/posts/排序', '/posts/排序', Record<never, never>, Record<never, never>>,
    '/posts/朴素贝叶斯': RouteRecordInfo<'/posts/朴素贝叶斯', '/posts/朴素贝叶斯', Record<never, never>, Record<never, never>>,
    '/posts/删除链表的倒数第N个结点': RouteRecordInfo<'/posts/删除链表的倒数第N个结点', '/posts/删除链表的倒数第N个结点', Record<never, never>, Record<never, never>>,
    '/posts/生信linux': RouteRecordInfo<'/posts/生信linux', '/posts/生信linux', Record<never, never>, Record<never, never>>,
    '/posts/使用archlinux参考文章': RouteRecordInfo<'/posts/使用archlinux参考文章', '/posts/使用archlinux参考文章', Record<never, never>, Record<never, never>>,
    '/posts/一些Tip': RouteRecordInfo<'/posts/一些Tip', '/posts/一些Tip', Record<never, never>, Record<never, never>>,
    '/posts/找出环形链表的入环第一个结点': RouteRecordInfo<'/posts/找出环形链表的入环第一个结点', '/posts/找出环形链表的入环第一个结点', Record<never, never>, Record<never, never>>,
    '/posts/重排链表': RouteRecordInfo<'/posts/重排链表', '/posts/重排链表', Record<never, never>, Record<never, never>>,
    '/slides/': RouteRecordInfo<'/slides/', '/slides', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
