/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/sky': RouteRecordInfo<'/albums/sky', '/albums/sky', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/fan/': RouteRecordInfo<'/fan/', '/fan', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/迭代-递归-分治': RouteRecordInfo<'/posts/迭代-递归-分治', '/posts/迭代-递归-分治', Record<never, never>, Record<never, never>>,
    '/posts/对链表插入排序': RouteRecordInfo<'/posts/对链表插入排序', '/posts/对链表插入排序', Record<never, never>, Record<never, never>>,
    '/posts/反转部分链表': RouteRecordInfo<'/posts/反转部分链表', '/posts/反转部分链表', Record<never, never>, Record<never, never>>,
    '/posts/反转链表': RouteRecordInfo<'/posts/反转链表', '/posts/反转链表', Record<never, never>, Record<never, never>>,
    '/posts/合并有序链表': RouteRecordInfo<'/posts/合并有序链表', '/posts/合并有序链表', Record<never, never>, Record<never, never>>,
    '/posts/回文数': RouteRecordInfo<'/posts/回文数', '/posts/回文数', Record<never, never>, Record<never, never>>,
    '/posts/机器学习': RouteRecordInfo<'/posts/机器学习', '/posts/机器学习', Record<never, never>, Record<never, never>>,
    '/posts/解决学习通鼠标移开暂停': RouteRecordInfo<'/posts/解决学习通鼠标移开暂停', '/posts/解决学习通鼠标移开暂停', Record<never, never>, Record<never, never>>,
    '/posts/解决vercel被墙的问题': RouteRecordInfo<'/posts/解决vercel被墙的问题', '/posts/解决vercel被墙的问题', Record<never, never>, Record<never, never>>,
    '/posts/决策树': RouteRecordInfo<'/posts/决策树', '/posts/决策树', Record<never, never>, Record<never, never>>,
    '/posts/链表': RouteRecordInfo<'/posts/链表', '/posts/链表', Record<never, never>, Record<never, never>>,
    '/posts/链表排序': RouteRecordInfo<'/posts/链表排序', '/posts/链表排序', Record<never, never>, Record<never, never>>,
    '/posts/排序': RouteRecordInfo<'/posts/排序', '/posts/排序', Record<never, never>, Record<never, never>>,
    '/posts/朴素贝叶斯': RouteRecordInfo<'/posts/朴素贝叶斯', '/posts/朴素贝叶斯', Record<never, never>, Record<never, never>>,
    '/posts/删除链表的倒数第N个结点': RouteRecordInfo<'/posts/删除链表的倒数第N个结点', '/posts/删除链表的倒数第N个结点', Record<never, never>, Record<never, never>>,
    '/posts/生信linux': RouteRecordInfo<'/posts/生信linux', '/posts/生信linux', Record<never, never>, Record<never, never>>,
    '/posts/使用Apriori算法进行关联分析': RouteRecordInfo<'/posts/使用Apriori算法进行关联分析', '/posts/使用Apriori算法进行关联分析', Record<never, never>, Record<never, never>>,
    '/posts/使用archlinux参考文章': RouteRecordInfo<'/posts/使用archlinux参考文章', '/posts/使用archlinux参考文章', Record<never, never>, Record<never, never>>,
    '/posts/使用FP-growth算法高效发现频繁项集': RouteRecordInfo<'/posts/使用FP-growth算法高效发现频繁项集', '/posts/使用FP-growth算法高效发现频繁项集', Record<never, never>, Record<never, never>>,
    '/posts/树回归': RouteRecordInfo<'/posts/树回归', '/posts/树回归', Record<never, never>, Record<never, never>>,
    '/posts/腾讯云cos图床+cloudflare+Picgo': RouteRecordInfo<'/posts/腾讯云cos图床+cloudflare+Picgo', '/posts/腾讯云cos图床+cloudflare+Picgo', Record<never, never>, Record<never, never>>,
    '/posts/图的存储': RouteRecordInfo<'/posts/图的存储', '/posts/图的存储', Record<never, never>, Record<never, never>>,
    '/posts/我的ff14之旅': RouteRecordInfo<'/posts/我的ff14之旅', '/posts/我的ff14之旅', Record<never, never>, Record<never, never>>,
    '/posts/一些Tip': RouteRecordInfo<'/posts/一些Tip', '/posts/一些Tip', Record<never, never>, Record<never, never>>,
    '/posts/预测数值型数据：回归': RouteRecordInfo<'/posts/预测数值型数据：回归', '/posts/预测数值型数据：回归', Record<never, never>, Record<never, never>>,
    '/posts/找出环形链表的入环第一个结点': RouteRecordInfo<'/posts/找出环形链表的入环第一个结点', '/posts/找出环形链表的入环第一个结点', Record<never, never>, Record<never, never>>,
    '/posts/重排链表': RouteRecordInfo<'/posts/重排链表', '/posts/重排链表', Record<never, never>, Record<never, never>>,
    '/posts/DFS_搜索': RouteRecordInfo<'/posts/DFS_搜索', '/posts/DFS_搜索', Record<never, never>, Record<never, never>>,
    '/posts/DFS_图论': RouteRecordInfo<'/posts/DFS_图论', '/posts/DFS_图论', Record<never, never>, Record<never, never>>,
    '/posts/ensemble-method': RouteRecordInfo<'/posts/ensemble-method', '/posts/ensemble-method', Record<never, never>, Record<never, never>>,
    '/posts/ff14高难奶轴': RouteRecordInfo<'/posts/ff14高难奶轴', '/posts/ff14高难奶轴', Record<never, never>, Record<never, never>>,
    '/posts/git基础教程': RouteRecordInfo<'/posts/git基础教程', '/posts/git基础教程', Record<never, never>, Record<never, never>>,
    '/posts/Github使用指南': RouteRecordInfo<'/posts/Github使用指南', '/posts/Github使用指南', Record<never, never>, Record<never, never>>,
    '/posts/Hexo博客迁移至Valaxy': RouteRecordInfo<'/posts/Hexo博客迁移至Valaxy', '/posts/Hexo博客迁移至Valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hexo初建站': RouteRecordInfo<'/posts/hexo初建站', '/posts/hexo初建站', Record<never, never>, Record<never, never>>,
    '/posts/K-Means 聚类算法': RouteRecordInfo<'/posts/K-Means 聚类算法', '/posts/K-Means 聚类算法', Record<never, never>, Record<never, never>>,
    '/posts/KNN近邻': RouteRecordInfo<'/posts/KNN近邻', '/posts/KNN近邻', Record<never, never>, Record<never, never>>,
    '/posts/linux一些命令': RouteRecordInfo<'/posts/linux一些命令', '/posts/linux一些命令', Record<never, never>, Record<never, never>>,
    '/posts/Logistic回归': RouteRecordInfo<'/posts/Logistic回归', '/posts/Logistic回归', Record<never, never>, Record<never, never>>,
    '/posts/LRU缓存': RouteRecordInfo<'/posts/LRU缓存', '/posts/LRU缓存', Record<never, never>, Record<never, never>>,
    '/posts/markdown的基础用法': RouteRecordInfo<'/posts/markdown的基础用法', '/posts/markdown的基础用法', Record<never, never>, Record<never, never>>,
    '/posts/missing-semester': RouteRecordInfo<'/posts/missing-semester', '/posts/missing-semester', Record<never, never>, Record<never, never>>,
    '/posts/SVM': RouteRecordInfo<'/posts/SVM', '/posts/SVM', Record<never, never>, Record<never, never>>,
    '/posts/valaxy版本升级指南': RouteRecordInfo<'/posts/valaxy版本升级指南', '/posts/valaxy版本升级指南', Record<never, never>, Record<never, never>>,
    '/posts/Vim简单应用': RouteRecordInfo<'/posts/Vim简单应用', '/posts/Vim简单应用', Record<never, never>, Record<never, never>>,
    '/slides/': RouteRecordInfo<'/slides/', '/slides', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
